import type { Lesson, QuizQuestion } from "@/types";

export interface Course {
  id: "money-foundations" | "macro-economy" | "money-flow" | "crypto-foundations" | "market-intelligence";
  title: string;
  oneLineSummary: string;
  lessonIds: string[];
}

export interface UniversityLesson {
  id: string;
  slug: string;
  title: string;
  shortSummary: string;
  oneLineSummary: string;
  learningObjectives: string[];
  explanation: string;
  whyItMatters: string;
  moneyFlowPosition: string;
  marketConnection: string;
  currentMarketConnection: string;
  relatedMetrics: string[];
  relatedCoins: string[];
  relatedNewsTopics: string[];
  relatedNews: string[];
  relatedNewsTags: string[];
  relatedChains: string[];
  relatedMacroFactors: string[];
  glossaryTerms: string[];
  aiMentorPrompts: string[];
  aiMentorQuestions: string[];
  previousLesson: string | null;
  nextLesson: string | null;
  prerequisites: string[];
  prerequisiteLessons: string[];
  relatedLessons: string[];
  estimatedReadingTime: number;
  estimatedMinutes: number;
  quiz: QuizQuestion[];
  courseId: Course["id"];
  difficulty: Lesson["difficulty"];
}

interface LessonInput {
  slug: string;
  courseId: Course["id"];
  title: string;
  shortSummary: string;
  learningObjectives: string[];
  explanation: string;
  whyItMatters: string;
  moneyFlowPosition: string;
  marketConnection: string;
  relatedMetrics: string[];
  relatedCoins: string[];
  relatedNewsTopics: string[];
  relatedChains: string[];
  relatedMacroFactors: string[];
  glossaryTerms: string[];
  aiMentorPrompts: string[];
  previousLesson: string | null;
  nextLesson: string | null;
  prerequisites: string[];
  relatedLessons: string[];
  estimatedReadingTime: number;
  difficulty: Lesson["difficulty"];
}

export const courses: Course[] = [
  {
    id: "money-foundations",
    title: "Money Foundations",
    oneLineSummary: "돈이 왜 움직이고, 어떤 형태로 머무는지부터 배웁니다.",
    lessonIds: ["what-is-money", "store-of-value-medium-unit", "liquidity-basics"],
  },
  {
    id: "macro-economy",
    title: "Macro Economy",
    oneLineSummary: "금리, 달러, 위험자산 선호가 돈의 이동 방향을 어떻게 바꾸는지 배웁니다.",
    lessonIds: ["interest-rates", "dollar-liquidity", "risk-assets"],
  },
  {
    id: "money-flow",
    title: "Money Flow",
    oneLineSummary: "거시경제에서 암호화폐 시장, 거래소, 체인, DeFi까지 이어지는 경로를 배웁니다.",
    lessonIds: ["money-flow", "stablecoin-pipeline", "exchange-chain-flow"],
  },
  {
    id: "crypto-foundations",
    title: "Crypto Foundations",
    oneLineSummary: "암호화폐, 블록체인, BTC, ETH, 스테이블코인, 토큰 구조를 배웁니다.",
    lessonIds: ["what-is-crypto", "blockchain-wallets", "consensus-transactions", "bitcoin-ethereum", "stablecoins", "crypto-classifications", "protocols-and-applications", "tokenomics"],
  },
  {
    id: "market-intelligence",
    title: "Market Intelligence",
    oneLineSummary: "TVL, 온체인 위험, 시장 종합 해석으로 학습을 마무리합니다.",
    lessonIds: ["tvl", "onchain-risk", "market-synthesis"],
  },
];

const lessonInputs: LessonInput[] = [
  {
    slug: "what-is-money",
    courseId: "money-foundations",
    title: "돈이란 무엇인가?",
    shortSummary: "돈은 가치를 저장하고, 교환을 쉽게 만들고, 가격을 비교하게 해주는 사회적 약속입니다.",
    learningObjectives: ["돈의 세 가지 기능을 설명한다", "시장 데이터에서 돈과 자산을 구분한다", "유동성을 공부하기 위한 기본 언어를 익힌다"],
    explanation: "돈은 단순한 종이나 숫자가 아니라 사람들이 받아들일 것이라고 믿는 교환 약속입니다. 이 약속이 있어야 노동, 상품, 자산의 가격을 비교할 수 있고 시간이 지나도 가치를 어느 정도 보관할 수 있습니다.",
    whyItMatters: "암호화폐 시장도 결국 돈이 어디에서 와서 어디에 머무는지의 문제입니다. 돈의 기능을 알면 가격표보다 자금의 이동 경로를 먼저 볼 수 있습니다.",
    moneyFlowPosition: "돈의 출발점입니다. 현금, 예금, 국채, 주식, 암호화폐로 이동하기 전 기준이 됩니다.",
    marketConnection: "세계 유동성과 금리 카드를 볼 때 돈이 위험자산으로 움직일 여유가 있는지 판단하는 기초가 됩니다.",
    relatedMetrics: ["global_liquidity", "fed_rate"],
    relatedCoins: ["btc"],
    relatedNewsTopics: ["macro", "regulation"],
    relatedChains: ["bitcoin"],
    relatedMacroFactors: ["liquidity", "interest-rate"],
    glossaryTerms: ["유동성", "시가총액"],
    aiMentorPrompts: ["돈과 유동성은 어떻게 다른가요?", "암호화폐를 돈의 관점에서 보면 무엇이 달라지나요?"],
    previousLesson: null,
    nextLesson: "store-of-value-medium-unit",
    prerequisites: [],
    relatedLessons: ["liquidity-basics", "interest-rates"],
    estimatedReadingTime: 6,
    difficulty: "beginner",
  },
  {
    slug: "store-of-value-medium-unit",
    courseId: "money-foundations",
    title: "가치 저장, 교환 수단, 계산 단위",
    shortSummary: "돈의 기능을 나누어 보면 비트코인, 달러, 스테이블코인이 서로 다른 역할을 하는 이유가 보입니다.",
    learningObjectives: ["돈의 기능을 세 부분으로 나눈다", "BTC와 스테이블코인의 역할 차이를 설명한다", "계산 단위가 시장 해석에 주는 영향을 이해한다"],
    explanation: "가치 저장은 시간이 지나도 구매력을 보관하는 기능이고, 교환 수단은 거래를 쉽게 만드는 기능입니다. 계산 단위는 모든 상품과 자산을 같은 기준으로 비교하게 해 줍니다. 암호화폐 시장에서는 BTC가 가치 저장 서사를 갖고, 스테이블코인이 교환 수단처럼 쓰이며, 달러가 계산 단위로 남는 경우가 많습니다.",
    whyItMatters: "서로 다른 코인을 같은 기준으로만 보면 역할을 혼동하기 쉽습니다. 돈의 기능을 나누면 어떤 자산이 시장 안에서 어떤 통로를 맡는지 더 분명해집니다.",
    moneyFlowPosition: "돈이 특정 형태로 머무는 이유를 설명하는 구간입니다. 가치 저장형 자산과 현금성 자산을 구분합니다.",
    marketConnection: "BTC 도미넌스와 스테이블코인 공급량을 함께 볼 때 자금이 저장을 택하는지 대기를 택하는지 비교할 수 있습니다.",
    relatedMetrics: ["btc_dominance", "stablecoin_supply"],
    relatedCoins: ["btc", "eth"],
    relatedNewsTopics: ["bitcoin", "stablecoin"],
    relatedChains: ["bitcoin", "ethereum"],
    relatedMacroFactors: ["dollar-liquidity", "risk-appetite"],
    glossaryTerms: ["스테이블코인", "비트코인 도미넌스"],
    aiMentorPrompts: ["BTC는 가치 저장 수단인가요?", "스테이블코인은 왜 시장 안의 현금처럼 보이나요?"],
    previousLesson: "what-is-money",
    nextLesson: "liquidity-basics",
    prerequisites: ["what-is-money"],
    relatedLessons: ["stablecoins", "bitcoin-ethereum"],
    estimatedReadingTime: 7,
    difficulty: "beginner",
  },
  {
    slug: "liquidity-basics",
    courseId: "money-foundations",
    title: "유동성이란 무엇인가?",
    shortSummary: "유동성은 자산을 큰 충격 없이 사고팔 수 있는 정도이자 시장에 움직일 수 있는 돈이 얼마나 있는지를 보는 언어입니다.",
    learningObjectives: ["거래 유동성과 거시 유동성을 구분한다", "유동성이 가격 변동성을 키우거나 낮추는 이유를 이해한다", "데이터 없음과 유동성 부족을 혼동하지 않는다"],
    explanation: "유동성은 두 층으로 볼 수 있습니다. 하나는 특정 자산을 사고팔 때 가격이 얼마나 흔들리는지이고, 다른 하나는 시장 전체에 위험자산으로 이동할 수 있는 돈이 얼마나 많은지입니다. 암호화폐는 두 층 모두에 민감합니다.",
    whyItMatters: "유동성이 약하면 좋은 뉴스가 있어도 가격이 지속되기 어렵고, 유동성이 풍부하면 작은 신호에도 자금이 빠르게 움직일 수 있습니다.",
    moneyFlowPosition: "돈이 정체되어 있는지, 움직일 수 있는 상태인지 판단하는 기초 필터입니다.",
    marketConnection: "세계 유동성, 스테이블코인 공급량, DeFi TVL이 서로 다른 층의 유동성을 보여줍니다.",
    relatedMetrics: ["global_liquidity", "stablecoin_supply", "defi_tvl"],
    relatedCoins: ["btc", "eth", "sol"],
    relatedNewsTopics: ["macro", "stablecoin", "defi"],
    relatedChains: ["bitcoin", "ethereum", "solana"],
    relatedMacroFactors: ["liquidity", "risk-appetite"],
    glossaryTerms: ["유동성", "TVL"],
    aiMentorPrompts: ["유동성이 많다는 말은 어떤 데이터를 봐야 하나요?", "스테이블코인 공급량과 세계 유동성은 같은 뜻인가요?"],
    previousLesson: "store-of-value-medium-unit",
    nextLesson: "interest-rates",
    prerequisites: ["what-is-money", "store-of-value-medium-unit"],
    relatedLessons: ["money-flow", "tvl"],
    estimatedReadingTime: 8,
    difficulty: "beginner",
  },
  {
    slug: "interest-rates",
    courseId: "macro-economy",
    title: "금리는 왜 돈의 방향을 바꿀까?",
    shortSummary: "금리는 안전한 곳에 머무는 보상과 위험자산으로 이동할 유인을 동시에 바꾸는 핵심 변수입니다.",
    learningObjectives: ["금리와 위험자산 선호의 관계를 설명한다", "높은 금리가 암호화폐 시장에 주는 부담을 이해한다", "금리를 단독 매매 신호로 쓰지 않는다"],
    explanation: "금리가 높아지면 안전한 이자를 받을 수 있는 선택지가 매력적이 됩니다. 그러면 위험이 큰 자산으로 이동하려면 더 강한 기대수익이나 명확한 근거가 필요합니다. 반대로 금리 부담이 낮아지면 위험자산으로 돈이 이동할 여지가 생길 수 있습니다.",
    whyItMatters: "암호화폐는 높은 변동성을 가진 위험자산으로 해석되는 경우가 많아 금리 변화에 민감하게 반응할 수 있습니다.",
    moneyFlowPosition: "거시경제에서 위험자산으로 넘어가는 첫 번째 문입니다. 돈이 안전한 이자에 머물지, 위험을 감수할지 결정하는 배경입니다.",
    marketConnection: "달러 금리 카드와 암호화폐 시가총액의 방향을 함께 보며 돈의 이동 압력을 확인합니다.",
    relatedMetrics: ["fed_rate", "crypto_market_cap"],
    relatedCoins: ["btc", "eth"],
    relatedNewsTopics: ["macro", "regulation"],
    relatedChains: ["bitcoin", "ethereum"],
    relatedMacroFactors: ["interest-rate", "risk-appetite"],
    glossaryTerms: ["유동성", "시가총액"],
    aiMentorPrompts: ["금리가 높으면 암호화폐는 항상 약한가요?", "금리와 유동성을 함께 봐야 하는 이유는 무엇인가요?"],
    previousLesson: "liquidity-basics",
    nextLesson: "dollar-liquidity",
    prerequisites: ["liquidity-basics"],
    relatedLessons: ["risk-assets", "money-flow"],
    estimatedReadingTime: 8,
    difficulty: "beginner",
  },
  {
    slug: "dollar-liquidity",
    courseId: "macro-economy",
    title: "달러 유동성은 왜 중요할까?",
    shortSummary: "달러는 암호화폐 시장의 주요 계산 단위이자 스테이블코인과 연결된 자금 통로입니다.",
    learningObjectives: ["달러 유동성과 스테이블코인의 관계를 이해한다", "강한 달러 환경이 위험자산에 주는 압력을 설명한다", "달러 지표와 온체인 지표를 연결한다"],
    explanation: "암호화폐 시장의 많은 가격과 거래쌍은 달러 또는 달러 기반 스테이블코인으로 표시됩니다. 그래서 달러가 부족하거나 비싸지는 환경은 시장 안의 대기 자금과 위험자산 선호에 영향을 줄 수 있습니다.",
    whyItMatters: "스테이블코인 공급이 늘어도 달러 유동성 환경이 나쁘면 그 돈이 곧바로 위험자산 매수로 이어진다고 단정하기 어렵습니다.",
    moneyFlowPosition: "현금성 자금이 암호화폐 시장 입구로 들어오는 통로를 해석하는 구간입니다.",
    marketConnection: "세계 유동성, 달러 금리, 스테이블코인 공급량을 함께 보며 시장 내부 대기 자금의 질을 판단합니다.",
    relatedMetrics: ["global_liquidity", "fed_rate", "stablecoin_supply"],
    relatedCoins: ["btc", "eth", "sol"],
    relatedNewsTopics: ["macro", "stablecoin", "exchange"],
    relatedChains: ["ethereum", "solana"],
    relatedMacroFactors: ["dollar-liquidity", "interest-rate"],
    glossaryTerms: ["스테이블코인", "유동성"],
    aiMentorPrompts: ["달러 유동성이 부족하면 스테이블코인 공급은 어떻게 해석해야 하나요?", "달러와 BTC 도미넌스는 어떤 관계로 볼 수 있나요?"],
    previousLesson: "interest-rates",
    nextLesson: "risk-assets",
    prerequisites: ["interest-rates"],
    relatedLessons: ["stablecoins", "stablecoin-pipeline"],
    estimatedReadingTime: 9,
    difficulty: "intermediate",
  },
  {
    slug: "risk-assets",
    courseId: "macro-economy",
    title: "위험자산 선호는 어떻게 생길까?",
    shortSummary: "위험자산 선호는 투자자가 안전한 수익보다 더 큰 변동성과 불확실성을 받아들이는 상태입니다.",
    learningObjectives: ["위험자산 선호와 회피를 구분한다", "암호화폐가 위험자산 흐름에서 어디에 있는지 설명한다", "반대 신호가 있을 때 단정하지 않는 태도를 익힌다"],
    explanation: "시장이 위험을 감수할 때 돈은 현금성 자산에서 주식, 신흥자산, 암호화폐처럼 변동성이 큰 곳으로 이동할 수 있습니다. 하지만 이 흐름은 금리, 뉴스, 유동성, 규제 신호에 따라 쉽게 약해질 수 있습니다.",
    whyItMatters: "암호화폐 상승과 하락을 코인 내부 뉴스만으로 설명하면 큰 시장 배경을 놓칠 수 있습니다.",
    moneyFlowPosition: "거시경제에서 암호화폐 시장으로 넘어가기 직전의 심리와 자금 조건을 다룹니다.",
    marketConnection: "암호화폐 시가총액과 BTC 도미넌스가 위험선호의 방향과 집중도를 보여주는 단서가 됩니다.",
    relatedMetrics: ["crypto_market_cap", "btc_dominance", "global_liquidity"],
    relatedCoins: ["btc", "eth", "sol"],
    relatedNewsTopics: ["macro", "bitcoin", "ethereum"],
    relatedChains: ["bitcoin", "ethereum", "solana"],
    relatedMacroFactors: ["risk-appetite", "liquidity"],
    glossaryTerms: ["비트코인 도미넌스", "시가총액"],
    aiMentorPrompts: ["위험선호가 강한지 약한지 어떤 지표로 확인하나요?", "BTC만 강하고 DeFi는 약하면 어떻게 해석하나요?"],
    previousLesson: "dollar-liquidity",
    nextLesson: "money-flow",
    prerequisites: ["dollar-liquidity"],
    relatedLessons: ["bitcoin-ethereum", "market-synthesis"],
    estimatedReadingTime: 8,
    difficulty: "intermediate",
  },
  {
    slug: "money-flow",
    courseId: "money-flow",
    title: "돈의 흐름은 어떻게 읽을까?",
    shortSummary: "거시경제에서 위험자산, 암호화폐 시장, 체인과 프로토콜로 이어지는 자금 이동을 추적합니다.",
    learningObjectives: ["돈의 이동 경로를 단계별로 설명한다", "지표 하나가 아니라 흐름 묶음으로 해석한다", "데이터 부족 시 판단을 보류한다"],
    explanation: "돈의 흐름은 Fed와 달러 환경에서 출발해 위험자산으로 이동하고, 암호화폐 시장 안에서는 BTC, ETH, 알트코인, DeFi, 스테이블코인, 거래소와 체인으로 나뉩니다. 이 흐름은 한 방향으로만 움직이지 않으며 일부 구간은 동시에 강하거나 약할 수 있습니다.",
    whyItMatters: "시장이 왜 오르거나 흔들리는지 설명하려면 가격보다 먼저 자금의 경로를 봐야 합니다.",
    moneyFlowPosition: "Macro Economy와 Crypto Foundations를 잇는 중심 허브입니다. 현금성 자금, BTC, ETH, DeFi로 이어지는 이동 경로를 연결합니다.",
    marketConnection: "돈의 흐름 엔진, 스테이블코인 공급량, 암호화폐 시가총액, DeFi TVL을 함께 해석합니다.",
    relatedMetrics: ["global_liquidity", "crypto_market_cap", "stablecoin_supply", "defi_tvl"],
    relatedCoins: ["btc", "eth", "sol"],
    relatedNewsTopics: ["macro", "stablecoin", "exchange", "defi"],
    relatedChains: ["bitcoin", "ethereum", "solana"],
    relatedMacroFactors: ["liquidity", "risk-appetite", "dollar-liquidity"],
    glossaryTerms: ["유동성", "비트코인 도미넌스", "TVL"],
    aiMentorPrompts: ["오늘 돈은 BTC 쪽에 가까운가요, DeFi 쪽에 가까운가요?", "스테이블코인 공급 증가를 바로 매수세로 봐도 되나요?"],
    previousLesson: "risk-assets",
    nextLesson: "stablecoin-pipeline",
    prerequisites: ["risk-assets"],
    relatedLessons: ["liquidity-basics", "market-synthesis"],
    estimatedReadingTime: 10,
    difficulty: "intermediate",
  },
  {
    slug: "stablecoin-pipeline",
    courseId: "money-flow",
    title: "스테이블코인 파이프라인",
    shortSummary: "스테이블코인은 시장 내부에서 현금성 자금이 대기하고 이동하는 통로로 자주 쓰입니다.",
    learningObjectives: ["스테이블코인 공급량을 대기 자금 관점에서 해석한다", "공급 증가와 실제 매수세를 구분한다", "거래소와 체인 이동을 함께 본다"],
    explanation: "스테이블코인이 늘어나는 것은 시장 안에 달러성 자금이 많아졌다는 단서가 될 수 있습니다. 하지만 그 자금이 거래소에 머무는지, 체인으로 이동하는지, DeFi에 예치되는지에 따라 의미가 달라집니다.",
    whyItMatters: "스테이블코인을 단순한 가격 보조 지표로 보면 실제 자금의 대기, 이동, 사용 여부를 놓치게 됩니다.",
    moneyFlowPosition: "암호화폐 시장 내부에서 현금성 자금이 BTC, ETH, 거래소, DeFi로 흘러가기 전 머무는 관문입니다.",
    marketConnection: "스테이블코인 공급량, 암호화폐 시가총액, DeFi TVL을 연결해 대기 자금이 실제 활동으로 이어지는지 봅니다.",
    relatedMetrics: ["stablecoin_supply", "crypto_market_cap", "defi_tvl"],
    relatedCoins: ["btc", "eth", "sol"],
    relatedNewsTopics: ["stablecoin", "exchange", "defi"],
    relatedChains: ["ethereum", "solana"],
    relatedMacroFactors: ["dollar-liquidity", "risk-appetite"],
    glossaryTerms: ["스테이블코인", "유동성", "TVL"],
    aiMentorPrompts: ["스테이블코인 공급 증가가 실제 매수세인지 어떻게 확인하나요?", "거래소로 들어간 스테이블코인은 어떤 한계가 있나요?"],
    previousLesson: "money-flow",
    nextLesson: "exchange-chain-flow",
    prerequisites: ["money-flow"],
    relatedLessons: ["stablecoins", "dollar-liquidity"],
    estimatedReadingTime: 9,
    difficulty: "intermediate",
  },
  {
    slug: "exchange-chain-flow",
    courseId: "money-flow",
    title: "거래소와 체인으로 흐르는 돈",
    shortSummary: "거래소와 체인은 돈이 대기, 거래, 예치, 이동 중 어디에 있는지 보여주는 서로 다른 관찰 지점입니다.",
    learningObjectives: ["거래소 흐름과 온체인 흐름을 구분한다", "체인 활동을 사용자 수로 단정하지 않는다", "자금 이동의 목적을 여러 가능성으로 나누어 본다"],
    explanation: "거래소로 들어간 자금은 거래 준비일 수도 있고 단순 보관 이동일 수도 있습니다. 체인으로 이동한 자금도 DeFi 사용, 브릿지, 내부 정리 등 여러 목적이 있을 수 있습니다. 그래서 숫자 하나보다 경로와 맥락을 함께 봐야 합니다.",
    whyItMatters: "거래소와 체인 신호를 단순하게 해석하면 실제 수요와 회계상 이동을 혼동할 수 있습니다.",
    moneyFlowPosition: "스테이블코인 대기 자금이 실제 거래와 온체인 활동으로 갈라지는 분기점입니다.",
    marketConnection: "거래소 뉴스, 체인별 활동, DeFi TVL을 함께 보며 시장 안의 돈이 어디에서 머무는지 확인합니다.",
    relatedMetrics: ["stablecoin_supply", "defi_tvl", "crypto_market_cap"],
    relatedCoins: ["btc", "eth", "sol"],
    relatedNewsTopics: ["exchange", "defi", "security"],
    relatedChains: ["bitcoin", "ethereum", "solana"],
    relatedMacroFactors: ["risk-appetite", "liquidity"],
    glossaryTerms: ["브릿지", "DeFi", "개인키"],
    aiMentorPrompts: ["거래소 유입은 항상 매도 압력인가요?", "체인 활동 증가를 사용자 증가로 봐도 되나요?"],
    previousLesson: "stablecoin-pipeline",
    nextLesson: "what-is-crypto",
    prerequisites: ["stablecoin-pipeline"],
    relatedLessons: ["onchain-risk", "tvl"],
    estimatedReadingTime: 9,
    difficulty: "intermediate",
  },
  {
    slug: "what-is-crypto",
    courseId: "crypto-foundations",
    title: "암호화폐는 무엇인가?",
    shortSummary: "암호화폐는 블록체인 네트워크에서 소유권과 거래가 기록되는 디지털 자산입니다.",
    learningObjectives: ["암호화폐와 블록체인의 관계를 설명한다", "소유권 기록의 의미를 이해한다", "코인 목적과 가격 움직임을 구분한다"],
    explanation: "암호화폐는 중앙 장부 하나에만 의존하지 않고 네트워크 참여자들이 규칙에 따라 소유권과 거래를 검증하는 디지털 자산입니다. 코인마다 목적이 다르기 때문에 단순히 가격만 비교하면 중요한 차이를 놓칠 수 있습니다. 다음 수업에서는 이 기록이 보관되는 블록체인과 사용자가 자산을 다루는 지갑, 개인키, 시드 문구를 배웁니다.",
    whyItMatters: "코인의 목적을 모르면 가격 움직임만 보고 잘못된 결론에 이르기 쉽습니다.",
    moneyFlowPosition: "위험자산으로 들어온 돈이 실제 디지털 네트워크 자산으로 바뀌는 지점입니다.",
    marketConnection: "암호화폐 전체 시가총액과 BTC 도미넌스를 통해 시장 규모와 집중도를 확인합니다.",
    relatedMetrics: ["crypto_market_cap", "btc_dominance"],
    relatedCoins: ["btc", "eth"],
    relatedNewsTopics: ["bitcoin", "ethereum", "regulation"],
    relatedChains: ["bitcoin", "ethereum"],
    relatedMacroFactors: ["risk-appetite"],
    glossaryTerms: ["블록체인", "개인키", "시가총액"],
    aiMentorPrompts: ["암호화폐와 블록체인은 어떻게 연결되나요?", "암호화폐를 주식처럼만 보면 어떤 점을 놓치나요?"],
    previousLesson: "exchange-chain-flow",
    nextLesson: "blockchain-wallets",
    prerequisites: ["exchange-chain-flow"],
    relatedLessons: ["blockchain-wallets", "tokenomics"],
    estimatedReadingTime: 7,
    difficulty: "beginner",
  },
  {
    slug: "blockchain-wallets",
    courseId: "crypto-foundations",
    title: "블록체인, 지갑, 개인키는 어떻게 연결될까?",
    shortSummary: "블록체인은 거래 기록을 보관하고, 지갑은 그 기록을 사용할 수 있게 해 주며, 개인키는 소유권을 증명합니다.",
    learningObjectives: ["블록체인을 공개 장부로 이해한다", "지갑과 개인키, 시드 문구의 차이를 설명한다", "수탁 지갑과 셀프 커스터디 지갑을 구분한다"],
    explanation: "블록체인은 거래 기록을 여러 참여자가 함께 보관하는 장부입니다. 지갑은 코인을 실제로 담는 주머니라기보다, 블록체인에 기록된 내 자산을 사용할 수 있게 해 주는 도구입니다. 개인키는 그 자산을 움직일 권한을 증명하는 비밀 열쇠이고, 시드 문구는 개인키를 복구하기 위한 매우 중요한 문장입니다. 거래소가 대신 보관해 주는 지갑은 수탁 지갑, 사용자가 직접 개인키를 관리하는 방식은 셀프 커스터디 지갑이라고 부릅니다. 다음 수업에서는 지갑이 거래를 보낼 때 네트워크가 어떻게 확인하고 수수료가 왜 생기는지 배웁니다.",
    whyItMatters: "지갑과 개인키를 이해하지 못하면 암호화폐의 소유권과 보관 위험을 제대로 이해하기 어렵습니다.",
    moneyFlowPosition: "돈이 거래소나 앱을 지나 개인 지갑과 체인 위 기록으로 이동하는 구간입니다.",
    marketConnection: "거래소 뉴스와 보안 뉴스는 자금이 수탁 지갑에 머무는지, 셀프 커스터디로 이동하는지 해석할 때 연결됩니다.",
    relatedMetrics: ["crypto_market_cap", "stablecoin_supply"],
    relatedCoins: ["btc", "eth", "sol"],
    relatedNewsTopics: ["exchange", "security", "regulation"],
    relatedChains: ["bitcoin", "ethereum", "solana"],
    relatedMacroFactors: ["risk-appetite", "liquidity"],
    glossaryTerms: ["블록체인", "개인키", "브릿지"],
    aiMentorPrompts: ["개인키와 시드 문구는 어떻게 다른가요?", "거래소 지갑과 셀프 커스터디 지갑은 어떤 점이 다른가요?"],
    previousLesson: "what-is-crypto",
    nextLesson: "consensus-transactions",
    prerequisites: ["what-is-crypto"],
    relatedLessons: ["exchange-chain-flow", "onchain-risk"],
    estimatedReadingTime: 8,
    difficulty: "beginner",
  },
  {
    slug: "consensus-transactions",
    courseId: "crypto-foundations",
    title: "거래, 수수료, 채굴, 합의 방식",
    shortSummary: "암호화폐 거래는 네트워크가 함께 확인하며, 수수료와 합의 방식은 체인의 작동 방식과 연결됩니다.",
    learningObjectives: ["거래와 수수료가 왜 필요한지 이해한다", "채굴과 Proof of Work를 설명한다", "Proof of Stake와 스테이킹의 기본 차이를 안다"],
    explanation: "암호화폐 거래는 지갑에서 보낸 요청이 네트워크에 전달되고, 참여자들이 규칙에 맞는지 확인한 뒤 블록에 기록되는 흐름으로 이해할 수 있습니다. 수수료는 이 거래를 처리하고 네트워크를 유지하는 데 쓰입니다. 비트코인은 채굴자가 계산 작업으로 블록을 만드는 Proof of Work 방식을 사용합니다. 이더리움과 솔라나 같은 여러 체인은 검증자가 맡긴 자산을 바탕으로 블록을 확인하는 Proof of Stake 방식을 씁니다. 여기서 스테이킹은 네트워크 검증에 참여하거나 그 보상 구조에 연결되는 활동입니다. 다음 수업에서는 이런 차이가 대표 프로젝트인 비트코인과 이더리움에서 어떻게 나타나는지 봅니다.",
    whyItMatters: "수수료와 합의 방식을 이해하면 왜 체인마다 속도, 비용, 보안, 에너지 사용 방식이 다른지 알 수 있습니다.",
    moneyFlowPosition: "돈이 실제 거래로 움직일 때 네트워크 비용과 검증 구조가 영향을 주는 구간입니다.",
    marketConnection: "체인 수수료와 네트워크 활동 관련 뉴스는 사용 증가인지 단순 혼잡인지 구분할 때 중요합니다.",
    relatedMetrics: ["crypto_market_cap", "defi_tvl"],
    relatedCoins: ["btc", "eth", "sol"],
    relatedNewsTopics: ["bitcoin", "ethereum", "defi", "security"],
    relatedChains: ["bitcoin", "ethereum", "solana"],
    relatedMacroFactors: ["risk-appetite", "liquidity"],
    glossaryTerms: ["블록체인", "스마트 계약", "가스비"],
    aiMentorPrompts: ["Proof of Work와 Proof of Stake는 어떻게 다른가요?", "수수료가 높아지면 돈의 흐름 해석에 어떤 영향을 주나요?"],
    previousLesson: "blockchain-wallets",
    nextLesson: "bitcoin-ethereum",
    prerequisites: ["blockchain-wallets"],
    relatedLessons: ["bitcoin-ethereum", "onchain-risk"],
    estimatedReadingTime: 9,
    difficulty: "beginner",
  },
  {
    slug: "bitcoin-ethereum",
    courseId: "crypto-foundations",
    title: "비트코인과 이더리움은 어떻게 다를까?",
    shortSummary: "비트코인은 희소성과 가치 저장 서사가 강하고, 이더리움은 앱과 스마트 계약 생태계가 핵심입니다.",
    learningObjectives: ["BTC와 ETH의 역할 차이를 설명한다", "도미넌스와 생태계 활동을 구분한다", "같은 암호화폐라도 돈의 흐름 위치가 다름을 이해한다"],
    explanation: "비트코인은 제한된 공급과 검열 저항성을 중심으로 가치 저장 서사를 갖습니다. 이더리움은 스마트 계약을 통해 DeFi, NFT, 다양한 앱을 실행하는 네트워크로 쓰입니다. 그래서 두 자산은 같은 시장에 있어도 돈이 머무는 이유가 다를 수 있습니다.",
    whyItMatters: "비트코인 도미넌스가 변할 때 시장 관심이 어디로 이동하는지 이해할 수 있습니다.",
    moneyFlowPosition: "암호화폐 시장 안에서 BTC 중심 흐름과 ETH 생태계 흐름을 구분하는 분기점입니다.",
    marketConnection: "BTC 도미넌스와 전체 시가총액을 함께 보며 자금 집중과 확산을 구분합니다.",
    relatedMetrics: ["btc_dominance", "crypto_market_cap"],
    relatedCoins: ["btc", "eth"],
    relatedNewsTopics: ["bitcoin", "ethereum"],
    relatedChains: ["bitcoin", "ethereum"],
    relatedMacroFactors: ["risk-appetite"],
    glossaryTerms: ["비트코인 도미넌스", "스마트 계약", "가스비"],
    aiMentorPrompts: ["BTC 도미넌스가 오르면 알트코인은 항상 약한가요?", "ETH와 BTC는 같은 지표로 비교해도 되나요?"],
    previousLesson: "consensus-transactions",
    nextLesson: "stablecoins",
    prerequisites: ["consensus-transactions"],
    relatedLessons: ["tvl", "risk-assets"],
    estimatedReadingTime: 8,
    difficulty: "beginner",
  },
  {
    slug: "stablecoins",
    courseId: "crypto-foundations",
    title: "스테이블코인은 왜 중요할까?",
    shortSummary: "스테이블코인은 시장 안에서 현금처럼 대기하거나 이동하는 자금 통로로 쓰입니다.",
    learningObjectives: ["스테이블코인의 역할을 설명한다", "공급량과 실제 수요를 구분한다", "디페깅과 준비금 위험을 이해한다"],
    explanation: "스테이블코인은 달러 같은 법정화폐 가치에 맞추도록 설계된 암호화폐입니다. 시장 참여자는 이를 거래 대기 자금, 송금, DeFi 담보로 활용합니다. 하지만 발행 구조, 준비금, 디페깅 위험을 함께 봐야 합니다.",
    whyItMatters: "암호화폐 시장의 유동성, 거래소 자금, 온체인 결제 흐름을 읽는 핵심 지표입니다.",
    moneyFlowPosition: "암호화폐 시장 내부의 현금성 대기 자금과 거래소·체인 이동을 보여주는 통로입니다.",
    marketConnection: "스테이블코인 공급량과 거래소·체인 노드를 연결해 대기 자금의 성격을 확인합니다.",
    relatedMetrics: ["stablecoin_supply", "crypto_market_cap"],
    relatedCoins: ["btc", "eth", "sol"],
    relatedNewsTopics: ["stablecoin", "exchange"],
    relatedChains: ["ethereum", "solana"],
    relatedMacroFactors: ["dollar-liquidity"],
    glossaryTerms: ["스테이블코인", "유동성"],
    aiMentorPrompts: ["스테이블코인 공급이 늘면 어떤 확인이 더 필요한가요?", "디페깅 뉴스는 돈의 흐름 해석에 어떤 영향을 주나요?"],
    previousLesson: "bitcoin-ethereum",
    nextLesson: "crypto-classifications",
    prerequisites: ["bitcoin-ethereum"],
    relatedLessons: ["stablecoin-pipeline", "crypto-classifications"],
    estimatedReadingTime: 8,
    difficulty: "beginner",
  },
  {
    slug: "crypto-classifications",
    courseId: "crypto-foundations",
    title: "암호화폐 분류는 어떻게 나눌까?",
    shortSummary: "코인, 토큰, Layer 1, Layer 2, 네이티브 자산, 앱 토큰처럼 비슷해 보이는 용어를 구분합니다.",
    learningObjectives: ["코인과 토큰을 구분한다", "Layer 1과 Layer 2를 예시로 설명한다", "유틸리티 토큰, 거버넌스 토큰, 밈코인, 프라이버시 코인, 거래소 토큰, RWA 토큰을 구분한다"],
    explanation: "코인은 보통 자체 블록체인의 기본 자산을 말합니다. 예를 들어 Bitcoin 네트워크의 BTC, Ethereum의 ETH, Solana의 SOL이 네이티브 코인입니다. 토큰은 이미 존재하는 체인 위에서 발행되는 자산입니다. 예를 들어 USDC, UNI, AAVE 같은 토큰은 특정 체인 위에서 발행되어 앱이나 프로토콜에서 쓰입니다. Layer 1은 Ethereum, Solana, Cardano, Avalanche, XRP Ledger처럼 기본 체인이고, Layer 2는 Arbitrum, Optimism, Polygon처럼 기존 체인의 처리 부담을 줄이거나 확장하는 네트워크로 이해할 수 있습니다. 변동성이 큰 자산과 스테이블코인, 유틸리티 토큰과 거버넌스 토큰, 밈코인과 프라이버시 코인, 거래소 토큰과 실물자산 토큰은 목적과 위험이 다르므로 한 덩어리로 보면 안 됩니다.",
    whyItMatters: "분류를 모르면 서로 다른 역할의 자산을 같은 기준으로 비교하게 됩니다. 분류를 이해하면 어떤 프로젝트가 체인인지, 앱인지, 토큰인지 먼저 구분할 수 있습니다.",
    moneyFlowPosition: "암호화폐 시장 안에서 돈이 어떤 종류의 자산으로 이동하는지 분류하는 단계입니다.",
    marketConnection: "시가총액, BTC 도미넌스, 스테이블코인 공급량은 돈이 네이티브 코인, 대기 자금, 앱 토큰 중 어디에 가까운지 볼 때 함께 쓰입니다.",
    relatedMetrics: ["crypto_market_cap", "btc_dominance", "stablecoin_supply"],
    relatedCoins: ["btc", "eth", "sol", "ada", "avax", "xrp", "matic", "arb", "op", "usdc", "usdt", "uni", "aave", "link"],
    relatedNewsTopics: ["bitcoin", "ethereum", "stablecoin", "defi", "regulation"],
    relatedChains: ["bitcoin", "ethereum", "solana", "cardano", "avalanche", "xrp-ledger", "polygon", "arbitrum", "optimism"],
    relatedMacroFactors: ["risk-appetite", "liquidity", "dollar-liquidity"],
    glossaryTerms: ["스테이블코인", "비트코인 도미넌스", "시가총액"],
    aiMentorPrompts: ["코인과 토큰은 초보자에게 어떻게 구분하면 좋나요?", "Layer 1과 Layer 2의 예시를 실제 프로젝트로 설명해 주세요."],
    previousLesson: "stablecoins",
    nextLesson: "protocols-and-applications",
    prerequisites: ["stablecoins"],
    relatedLessons: ["what-is-crypto", "tokenomics"],
    estimatedReadingTime: 11,
    difficulty: "beginner",
  },
  {
    slug: "protocols-and-applications",
    courseId: "crypto-foundations",
    title: "프로토콜과 애플리케이션은 어떻게 다를까?",
    shortSummary: "블록체인, 프로토콜, 애플리케이션, 토큰이 서로 다른 층에 있다는 점을 실제 프로젝트로 배웁니다.",
    learningObjectives: ["블록체인과 프로토콜을 구분한다", "DEX, 대출 프로토콜, 오라클, 브릿지, NFT를 예시로 설명한다", "중앙화 거래소와 탈중앙화 거래소를 구분한다"],
    explanation: "블록체인은 앱이 올라가는 기반 네트워크입니다. Ethereum이나 Solana가 예입니다. 프로토콜은 그 체인 위에서 특정 규칙으로 작동하는 서비스입니다. Uniswap은 탈중앙화 거래소, Aave는 대출 프로토콜, Chainlink는 외부 데이터를 연결하는 오라클, Maker 또는 Sky는 스테이블코인과 대출 구조를 가진 프로토콜로 볼 수 있습니다. 중앙화 거래소는 회사가 주문과 보관을 관리하지만, 탈중앙화 거래소는 스마트 계약이 교환 규칙을 실행합니다. NFT는 고유한 디지털 소유권을 표현하는 토큰이고, 브릿지는 체인 사이로 자산을 옮기는 통로입니다. 다음 수업에서는 이런 토큰들이 어떤 공급 구조와 권한을 갖는지 토큰 경제학으로 정리합니다.",
    whyItMatters: "체인, 프로토콜, 앱, 토큰을 구분하지 못하면 프로젝트의 역할과 위험을 잘못 이해하기 쉽습니다.",
    moneyFlowPosition: "돈이 네이티브 코인을 넘어 DeFi, NFT, 오라클, 브릿지 같은 실제 사용처로 이동하는 구간입니다.",
    marketConnection: "DeFi TVL과 보안 뉴스는 앱과 프로토콜에 돈이 머무는지, 위험 때문에 빠지는지 볼 때 연결됩니다.",
    relatedMetrics: ["defi_tvl", "crypto_market_cap", "stablecoin_supply"],
    relatedCoins: ["eth", "sol", "uni", "aave", "link", "maker", "usdc", "usdt"],
    relatedNewsTopics: ["defi", "security", "stablecoin", "exchange"],
    relatedChains: ["ethereum", "solana", "polygon", "arbitrum", "optimism"],
    relatedMacroFactors: ["risk-appetite", "liquidity"],
    glossaryTerms: ["DeFi", "스마트 계약", "브릿지", "TVL"],
    aiMentorPrompts: ["블록체인, 프로토콜, 토큰을 실제 예시로 구분해 주세요.", "중앙화 거래소와 탈중앙화 거래소는 무엇이 다른가요?"],
    previousLesson: "crypto-classifications",
    nextLesson: "tokenomics",
    prerequisites: ["crypto-classifications"],
    relatedLessons: ["tvl", "onchain-risk"],
    estimatedReadingTime: 11,
    difficulty: "beginner",
  },
  {
    slug: "tokenomics",
    courseId: "crypto-foundations",
    title: "토큰 경제학은 왜 중요할까?",
    shortSummary: "토큰 경제학은 공급량, 유통량, 보상, 락업처럼 토큰 가치에 영향을 주는 구조를 봅니다.",
    learningObjectives: ["시가총액과 공급 구조를 함께 본다", "락업과 보상이 돈의 흐름에 주는 영향을 이해한다", "토큰 가격과 네트워크 가치의 차이를 구분한다"],
    explanation: "토큰은 단순한 가격표가 아니라 발행, 유통, 보상, 소각, 락업 같은 규칙의 묶음입니다. 같은 돈이 들어와도 유통량이 빠르게 늘어나면 가격에 반영되는 방식이 달라질 수 있습니다.",
    whyItMatters: "시가총액과 FDV를 비교하면 현재 가격이 어떤 공급 구조 위에 있는지 더 잘 이해할 수 있습니다.",
    moneyFlowPosition: "시장으로 들어온 돈이 특정 토큰 가격에 반영될 때 공급 구조가 병목이 되는 구간입니다.",
    marketConnection: "전체 시가총액만으로는 보이지 않는 공급 부담과 유통 구조를 함께 점검합니다.",
    relatedMetrics: ["crypto_market_cap"],
    relatedCoins: ["btc", "eth", "sol"],
    relatedNewsTopics: ["bitcoin", "ethereum", "defi"],
    relatedChains: ["bitcoin", "ethereum", "solana"],
    relatedMacroFactors: ["risk-appetite"],
    glossaryTerms: ["시가총액"],
    aiMentorPrompts: ["시가총액과 공급 구조를 같이 봐야 하는 이유는 무엇인가요?", "락업 해제는 항상 나쁜 신호인가요?"],
    previousLesson: "protocols-and-applications",
    nextLesson: "tvl",
    prerequisites: ["protocols-and-applications"],
    relatedLessons: ["what-is-crypto", "market-synthesis"],
    estimatedReadingTime: 9,
    difficulty: "intermediate",
  },
  {
    slug: "tvl",
    courseId: "market-intelligence",
    title: "TVL은 무엇인가?",
    shortSummary: "TVL은 디파이 프로토콜에 예치된 자산의 총 가치를 뜻합니다.",
    learningObjectives: ["TVL의 의미와 한계를 설명한다", "가격 상승 효과와 실제 예치 증가를 구분한다", "DeFi 활동을 돈의 흐름 관점에서 해석한다"],
    explanation: "TVL은 DeFi 프로토콜에 예치된 자산 가치를 합산한 지표입니다. 하지만 자산 가격이 오르면 실제 예치 수량이 늘지 않아도 TVL이 증가할 수 있습니다. 그래서 TVL은 가격, 인센티브, 보안 뉴스와 함께 봐야 합니다.",
    whyItMatters: "온체인 생태계에 돈이 머무는지 빠지는지 판단하는 대표 지표입니다.",
    moneyFlowPosition: "BTC와 ETH를 지나 DeFi 프로토콜까지 돈이 확산되는지 확인하는 구간입니다.",
    marketConnection: "DeFi TVL 카드와 ETH, SOL 체인 활동을 연결해 생태계 자금 체류를 봅니다.",
    relatedMetrics: ["defi_tvl"],
    relatedCoins: ["eth", "sol"],
    relatedNewsTopics: ["defi", "security"],
    relatedChains: ["ethereum", "solana"],
    relatedMacroFactors: ["risk-appetite"],
    glossaryTerms: ["TVL", "DeFi", "스마트 계약"],
    aiMentorPrompts: ["TVL 증가가 실제 사용 증가인지 어떻게 구분하나요?", "TVL과 토큰 가격은 왜 다르게 움직일 수 있나요?"],
    previousLesson: "tokenomics",
    nextLesson: "onchain-risk",
    prerequisites: ["tokenomics"],
    relatedLessons: ["exchange-chain-flow", "stablecoin-pipeline"],
    estimatedReadingTime: 7,
    difficulty: "beginner",
  },
  {
    slug: "onchain-risk",
    courseId: "market-intelligence",
    title: "온체인 데이터의 위험은 어떻게 봐야 할까?",
    shortSummary: "지갑, 거래, TVL, 브릿지 흐름 같은 온체인 데이터는 투명하지만 해석에는 한계가 있습니다.",
    learningObjectives: ["온체인 데이터의 장점과 한계를 설명한다", "활성 주소와 실제 사용자를 구분한다", "보안과 브릿지 위험을 돈의 흐름에 연결한다"],
    explanation: "온체인 데이터는 공개되어 있지만 모든 의미가 자동으로 드러나는 것은 아닙니다. 하나의 사용자가 여러 주소를 쓸 수 있고, 내부 이동이 실제 수요처럼 보일 수 있으며, 브릿지와 스마트 계약 위험은 자금 이동을 갑자기 막을 수 있습니다.",
    whyItMatters: "숫자의 의미와 한계를 함께 이해하면 과열과 착시를 더 잘 구분할 수 있습니다.",
    moneyFlowPosition: "돈의 흐름을 마지막으로 검증하는 안전장치입니다. 체인 데이터가 실제 사용자, 자금, 위험 중 무엇을 보여주는지 구분합니다.",
    marketConnection: "DeFi TVL, 관련 뉴스, 체인 활동을 함께 보며 데이터 부족이나 해석 한계를 확인합니다.",
    relatedMetrics: ["defi_tvl"],
    relatedCoins: ["btc", "eth", "sol"],
    relatedNewsTopics: ["security", "defi", "exchange"],
    relatedChains: ["bitcoin", "ethereum", "solana"],
    relatedMacroFactors: ["risk-appetite", "liquidity"],
    glossaryTerms: ["브릿지", "개인키", "DeFi"],
    aiMentorPrompts: ["활성 주소를 사용자 수로 봐도 되나요?", "온체인 데이터가 부족하면 어떤 결론을 피해야 하나요?"],
    previousLesson: "tvl",
    nextLesson: "market-synthesis",
    prerequisites: ["tvl"],
    relatedLessons: ["exchange-chain-flow", "market-synthesis"],
    estimatedReadingTime: 9,
    difficulty: "intermediate",
  },
  {
    slug: "market-synthesis",
    courseId: "market-intelligence",
    title: "시장 해석은 어떻게 종합할까?",
    shortSummary: "시장 해석은 거시 환경, 시장 규모, 스테이블코인, 온체인 활동, 뉴스의 한계를 함께 묶는 과정입니다.",
    learningObjectives: ["여러 지표를 한 문장으로 종합한다", "근거와 반대 신호를 함께 제시한다", "투자 추천 없이 학습 관점의 해설을 작성한다"],
    explanation: "좋은 시장 해석은 하나의 강한 신호만 고르는 일이 아닙니다. 거시 유동성, 금리, 시가총액, 도미넌스, 스테이블코인, TVL, 뉴스와 데이터 상태를 함께 놓고 어디까지 말할 수 있고 어디부터는 판단을 보류해야 하는지 나눕니다.",
    whyItMatters: "초보자는 결론부터 찾기 쉽지만, 안전한 학습 시스템은 근거와 한계를 같이 보는 습관을 만들어야 합니다.",
    moneyFlowPosition: "전체 파이프라인의 마지막 해석 단계입니다. 돈이 어디로 움직이는지와 무엇을 아직 모르는지를 정리합니다.",
    marketConnection: "홈 화면의 오늘 요약, 돈의 흐름 엔진, 뉴스 연결, 관련 학습 추천을 한 번에 연결합니다.",
    relatedMetrics: ["global_liquidity", "fed_rate", "crypto_market_cap", "btc_dominance", "stablecoin_supply", "defi_tvl"],
    relatedCoins: ["btc", "eth", "sol"],
    relatedNewsTopics: ["macro", "bitcoin", "ethereum", "stablecoin", "defi", "security"],
    relatedChains: ["bitcoin", "ethereum", "solana"],
    relatedMacroFactors: ["liquidity", "interest-rate", "dollar-liquidity", "risk-appetite"],
    glossaryTerms: ["유동성", "비트코인 도미넌스", "TVL"],
    aiMentorPrompts: ["오늘 시장 해석에서 가장 강한 근거와 약한 근거는 무엇인가요?", "데이터가 부족하면 어떻게 표현해야 하나요?"],
    previousLesson: "onchain-risk",
    nextLesson: null,
    prerequisites: ["onchain-risk"],
    relatedLessons: ["money-flow", "risk-assets"],
    estimatedReadingTime: 10,
    difficulty: "intermediate",
  },
];

export function courseForLesson(lessonId: string) {
  const item = universityLessonsById.get(lessonId);
  return item ? courses.find((course) => course.id === item.courseId) : undefined;
}

export function moduleForLesson(lessonId: string) {
  const item = universityLessonsById.get(lessonId);
  const course = item ? courses.find((candidate) => candidate.id === item.courseId) : undefined;
  if (!item || !course) return undefined;
  const index = course.lessonIds.indexOf(item.id);
  return {
    index: index >= 0 ? index + 1 : 1,
    title: `Module ${index >= 0 ? index + 1 : 1}`,
    total: course.lessonIds.length,
  };
}

export function toLegacyLesson(item: UniversityLesson): Lesson {
  return {
    id: item.id,
    slug: item.slug,
    categoryId: courses.find((course) => course.id === item.courseId)?.title ?? item.courseId,
    title: item.title,
    summary: item.shortSummary,
    simpleExplanation: item.shortSummary,
    analogy: item.moneyFlowPosition,
    detailedExplanation: `먼저 핵심 개념부터 봅니다. ${item.explanation} 다음으로 왜 중요한지 연결합니다. ${item.whyItMatters} 마지막으로 현재 시장과 연결합니다. ${item.marketConnection} 다만 하나의 지표나 뉴스만으로 시장 방향을 확정하지는 않습니다.`,
    whyItMatters: item.whyItMatters,
    examples: [
      { title: "학습 목표", description: item.learningObjectives.join(" / ") },
      { title: "돈의 흐름에서 위치", description: item.moneyFlowPosition },
      { title: "다음 학습으로 연결", description: item.nextLesson ? `이 수업은 다음 수업인 ${universityLessonsById.get(item.nextLesson)?.title ?? item.nextLesson}로 이어집니다.` : "이 수업은 전체 시장 해석을 마무리하는 마지막 단계입니다." },
      { title: "AI Mentor 질문", description: item.aiMentorPrompts.join(" / ") },
    ],
    misconceptions: ["하나의 뉴스나 지표만으로 가격 방향을 확정할 수 없습니다."],
    risks: ["데이터 지연, 출처 차이, 해석 오류를 항상 함께 봐야 합니다."],
    relatedTerms: item.glossaryTerms,
    relatedMetricIds: item.relatedMetrics,
    prerequisites: item.prerequisites,
    nextLessons: item.nextLesson ? [item.nextLesson] : [],
    quiz: item.quiz,
    difficulty: item.difficulty,
    estimatedMinutes: item.estimatedReadingTime,
  };
}

function lesson(input: LessonInput): UniversityLesson {
  return {
    ...input,
    id: input.slug,
    oneLineSummary: input.shortSummary,
    currentMarketConnection: input.marketConnection,
    relatedNews: input.relatedNewsTopics,
    relatedNewsTags: input.relatedNewsTopics,
    aiMentorQuestions: input.aiMentorPrompts,
    prerequisiteLessons: input.prerequisites,
    estimatedMinutes: input.estimatedReadingTime,
    quiz: [quizBySlug[input.slug] ?? defaultQuiz(input.title)],
  };
}

function defaultQuiz(title: string): QuizQuestion {
  return {
    question: `${title}를 공부할 때 가장 안전한 태도는 무엇일까요?`,
    options: ["근거와 한계를 함께 본다", "가격 방향을 바로 확정한다", "데이터가 없으면 0으로 본다", "뉴스 하나만 믿는다"],
    answerIndex: 0,
    explanation: "학습 시스템은 연결된 지표, 뉴스, 용어, 한계를 함께 보도록 설계되어 있습니다.",
  };
}

const quizBySlug: Record<string, QuizQuestion> = {
  "what-is-money": {
    question: "이 수업에서 말하는 돈의 가장 중요한 특징은 무엇인가요?",
    options: ["사람들이 함께 믿고 쓰는 약속이라는 점", "가격이 항상 오르는 자산이라는 점", "암호화폐와 완전히 같은 것이라는 점", "정부가 없어도 항상 안정적이라는 점"],
    answerIndex: 0,
    explanation: "돈은 사람들이 받아들인다는 믿음 위에서 작동합니다. 그래서 돈의 흐름을 보려면 먼저 그 약속이 어디에 머무는지 봐야 합니다.",
  },
  "store-of-value-medium-unit": {
    question: "스테이블코인이 시장 안에서 자주 맡는 역할에 가장 가까운 것은 무엇인가요?",
    options: ["거래하거나 대기하는 현금성 통로", "항상 가치가 오르는 성장 자산", "채굴 보상을 주는 전용 장비", "모든 체인의 거래 수수료"],
    answerIndex: 0,
    explanation: "스테이블코인은 시장 안에서 달러처럼 대기하거나 이동하는 통로로 자주 쓰입니다.",
  },
  "liquidity-basics": {
    question: "유동성을 가장 쉽게 설명한 문장은 무엇인가요?",
    options: ["돈이나 자산이 얼마나 쉽게 움직일 수 있는지", "코인의 이름이 얼마나 유명한지", "뉴스가 몇 개나 나왔는지", "가격이 하루에 반드시 오르는 정도"],
    answerIndex: 0,
    explanation: "유동성은 움직임의 쉬움과 관련됩니다. 시장에 돈과 거래 상대가 많을수록 자산이 더 쉽게 움직일 수 있습니다.",
  },
  "interest-rates": {
    question: "금리가 높을 때 위험자산에 부담이 될 수 있는 이유는 무엇인가요?",
    options: ["안전한 곳에 머물러도 받을 수 있는 보상이 커지기 때문", "모든 코인의 공급량이 자동으로 줄어들기 때문", "블록체인이 멈추기 때문", "뉴스가 모두 사라지기 때문"],
    answerIndex: 0,
    explanation: "금리가 높으면 안전한 선택지도 매력적입니다. 그래서 위험자산으로 돈이 이동하려면 더 강한 이유가 필요합니다.",
  },
  "dollar-liquidity": {
    question: "스테이블코인 공급이 늘어도 바로 매수세라고 단정하면 안 되는 이유는 무엇인가요?",
    options: ["달러 환경과 실제 이동 경로를 함께 확인해야 하기 때문", "스테이블코인은 항상 가치가 0이 되기 때문", "BTC 도미넌스와 전혀 관련이 없기 때문", "금리는 암호화폐와 절대 관련이 없기 때문"],
    answerIndex: 0,
    explanation: "스테이블코인은 대기 자금의 단서일 수 있지만, 그 돈이 실제로 어디로 움직이는지 추가 확인이 필요합니다.",
  },
  "risk-assets": {
    question: "위험자산 선호가 강해졌다는 말에 가장 가까운 설명은 무엇인가요?",
    options: ["사람들이 더 큰 변동성을 감수하고 수익 기회를 찾는 상태", "모든 투자자가 현금만 보유하는 상태", "뉴스를 전혀 보지 않는 상태", "블록체인의 거래가 모두 사라지는 상태"],
    answerIndex: 0,
    explanation: "위험자산 선호는 돈이 안전한 곳에서 더 변동성이 큰 자산으로 움직일 수 있는 분위기를 뜻합니다.",
  },
  "money-flow": {
    question: "돈의 흐름을 읽을 때 가장 좋은 태도는 무엇인가요?",
    options: ["여러 구간의 신호를 나누어 보고 강한 곳과 약한 곳을 구분한다", "가격이 오른 코인 하나만 보고 결론낸다", "데이터가 없으면 0으로 처리한다", "뉴스 제목만 보고 방향을 확정한다"],
    answerIndex: 0,
    explanation: "돈의 흐름은 여러 구간으로 나누어 봐야 합니다. 한 지표만으로 전체 방향을 확정하면 오해하기 쉽습니다.",
  },
  "stablecoin-pipeline": {
    question: "스테이블코인 공급 증가를 해석할 때 가장 중요한 추가 확인은 무엇인가요?",
    options: ["그 자금이 거래소, 체인, DeFi 중 어디로 이동하는지", "코인 이름이 얼마나 짧은지", "차트 색상이 무엇인지", "모든 뉴스가 긍정적인지"],
    answerIndex: 0,
    explanation: "공급 증가는 대기 자금의 단서일 수 있지만, 실제 해석은 그 자금이 어디로 움직이는지와 함께 봐야 합니다.",
  },
  "exchange-chain-flow": {
    question: "거래소 유입이나 체인 활동을 볼 때 피해야 할 해석은 무엇인가요?",
    options: ["하나의 이동을 무조건 매수나 매도로 단정하는 것", "여러 가능성을 함께 보는 것", "관련 뉴스와 지표를 확인하는 것", "데이터 상태를 확인하는 것"],
    answerIndex: 0,
    explanation: "자금 이동에는 여러 이유가 있을 수 있습니다. 거래소와 체인 데이터는 방향을 단정하기보다 가능성을 좁히는 자료로 봐야 합니다.",
  },
  "what-is-crypto": {
    question: "암호화폐를 이해할 때 가장 먼저 구분해야 하는 것은 무엇인가요?",
    options: ["각 코인이 어떤 목적과 역할을 갖는지", "로고 색상이 무엇인지", "가격이 어제보다 올랐는지만", "거래소 이름이 얼마나 유명한지"],
    answerIndex: 0,
    explanation: "코인마다 목적이 다릅니다. 목적을 알아야 돈이 왜 그 자산으로 이동하는지 해석할 수 있습니다.",
  },
  "blockchain-wallets": {
    question: "개인키를 가장 잘 설명한 것은 무엇인가요?",
    options: ["블록체인에 기록된 자산을 움직일 권한을 증명하는 비밀 정보", "거래소의 고객센터 비밀번호", "코인의 현재 가격표", "블록체인의 공개 뉴스 목록"],
    answerIndex: 0,
    explanation: "개인키는 자산을 움직일 권한과 연결됩니다. 그래서 시드 문구와 함께 매우 조심해서 보관해야 합니다.",
  },
  "consensus-transactions": {
    question: "Proof of Work와 Proof of Stake를 구분하는 설명으로 가장 알맞은 것은 무엇인가요?",
    options: ["PoW는 계산 작업, PoS는 맡긴 자산과 검증자를 중심으로 블록을 확인한다", "둘 다 중앙 회사가 모든 거래를 승인한다", "PoS는 거래 수수료가 절대 없다", "PoW는 지갑이 필요 없는 방식이다"],
    answerIndex: 0,
    explanation: "비트코인은 PoW의 대표 예시이고, 이더리움은 PoS 방식으로 운영됩니다. 둘은 네트워크를 확인하는 방식이 다릅니다.",
  },
  "bitcoin-ethereum": {
    question: "이 수업에서 설명한 BTC와 ETH의 차이에 가장 가까운 것은 무엇인가요?",
    options: ["BTC는 가치 저장 이야기, ETH는 앱과 스마트 계약 생태계와 가깝다", "둘은 완전히 같은 역할만 한다", "ETH는 블록체인과 관련이 없다", "BTC는 DeFi 앱 실행만을 위해 만들어졌다"],
    answerIndex: 0,
    explanation: "BTC와 ETH는 모두 암호화폐지만 돈이 머무는 이유와 시장에서 보는 역할이 다를 수 있습니다.",
  },
  stablecoins: {
    question: "스테이블코인을 해석할 때 가장 조심해야 할 점은 무엇인가요?",
    options: ["공급량만 보고 바로 매수세라고 단정하지 않는 것", "항상 가격이 크게 오른다고 믿는 것", "준비금과 디페깅 위험을 보지 않는 것", "시장 유동성과 완전히 무관하다고 보는 것"],
    answerIndex: 0,
    explanation: "스테이블코인 공급은 중요한 단서지만, 실제 자금 이동과 위험을 함께 확인해야 합니다.",
  },
  "crypto-classifications": {
    question: "코인과 토큰을 구분하는 설명으로 가장 알맞은 것은 무엇인가요?",
    options: ["코인은 자체 체인의 기본 자산이고, 토큰은 기존 체인 위에서 발행되는 자산인 경우가 많다", "코인과 토큰은 항상 완전히 같은 뜻이다", "토큰은 블록체인과 아무 관련이 없다", "Layer 2는 항상 스테이블코인만 뜻한다"],
    answerIndex: 0,
    explanation: "BTC, ETH, SOL은 네이티브 코인 예시이고, USDC, UNI, AAVE 같은 자산은 기존 체인 위의 토큰 예시로 볼 수 있습니다.",
  },
  "protocols-and-applications": {
    question: "블록체인과 프로토콜의 관계를 가장 잘 설명한 것은 무엇인가요?",
    options: ["블록체인은 기반 네트워크이고, 프로토콜은 그 위에서 특정 기능을 실행하는 서비스다", "프로토콜은 항상 중앙화 거래소만 뜻한다", "블록체인은 앱 위에 설치되는 작은 버튼이다", "오라클은 NFT와 항상 같은 뜻이다"],
    answerIndex: 0,
    explanation: "Ethereum 같은 체인 위에서 Uniswap, Aave, Chainlink 같은 프로토콜이 작동할 수 있습니다.",
  },
  tokenomics: {
    question: "토큰 경제학에서 함께 봐야 하는 요소로 가장 알맞은 것은 무엇인가요?",
    options: ["발행량, 유통량, 락업, 보상 구조", "로고 디자인과 이름 길이", "하루 동안의 검색량만", "거래소 앱의 색상"],
    answerIndex: 0,
    explanation: "토큰 가격은 돈의 유입뿐 아니라 공급 구조의 영향을 받습니다. 그래서 발행량과 유통량 같은 요소를 함께 봐야 합니다.",
  },
  tvl: {
    question: "TVL이 늘었을 때 바로 확인해야 할 것은 무엇인가요?",
    options: ["실제 예치가 늘었는지, 자산 가격 상승 효과인지", "모든 DeFi가 안전해졌는지", "금리가 사라졌는지", "비트코인 공급량이 늘었는지"],
    answerIndex: 0,
    explanation: "TVL은 자산 가격 변화만으로도 늘 수 있습니다. 실제 자금 유입인지 확인해야 더 안전하게 해석할 수 있습니다.",
  },
  "onchain-risk": {
    question: "온체인 데이터를 볼 때 가장 조심해야 할 해석은 무엇인가요?",
    options: ["활성 주소를 곧바로 실제 사용자 수로 단정하는 것", "데이터 출처를 확인하는 것", "관련 뉴스와 함께 보는 것", "한계를 표시하는 것"],
    answerIndex: 0,
    explanation: "한 사람이 여러 주소를 쓸 수 있고 내부 이동도 있을 수 있습니다. 그래서 활성 주소를 바로 사용자 수로 단정하면 위험합니다.",
  },
  "market-synthesis": {
    question: "시장 해석을 종합할 때 가장 안전한 방식은 무엇인가요?",
    options: ["근거, 반대 신호, 모르는 부분을 함께 정리한다", "가장 마음에 드는 지표 하나만 고른다", "가격 예측을 확정적으로 말한다", "데이터 상태는 보지 않는다"],
    answerIndex: 0,
    explanation: "학습용 시장 해석은 확정 예측이 아니라 근거와 한계를 함께 정리하는 과정입니다.",
  },
};

export const universityLessons: UniversityLesson[] = lessonInputs.map(lesson);
export const universityLessonsById = new Map(universityLessons.map((item) => [item.id, item]));
