import type { Lesson } from "@/types";

export const lessonCategories = [
  "돈과 화폐",
  "암호화폐란 무엇인가",
  "블록체인 기초",
  "비트코인",
  "스마트 계약과 이더리움",
  "암호화폐의 종류",
  "블록체인 생태계 구조",
  "중앙화 거래소",
  "탈중앙화 금융",
  "스테이블코인",
  "토큰 경제학",
  "NFT, 게임, DePIN, AI, RWA",
  "지갑과 보안",
  "온체인 데이터",
  "암호화폐 시장 분석",
  "위험과 사기 유형",
  "규제와 세금 기초",
];

export const lessons: Lesson[] = [
  {
    id: "money-basics",
    slug: "what-is-money",
    categoryId: "돈과 화폐",
    title: "돈은 무엇인가?",
    summary: "돈은 가치를 저장하고, 교환하고, 가격을 비교하게 해주는 사회적 약속입니다.",
    simpleExplanation: "돈은 모두가 받아준다고 믿기 때문에 쓸 수 있는 도구입니다.",
    analogy: "동네 쿠폰이 그 동네에서만 통하듯, 돈도 사람들이 믿고 받아주는 범위가 중요합니다.",
    detailedExplanation:
      "돈은 가치 저장, 교환 매개, 회계 단위라는 세 가지 기능을 갖습니다. 암호화폐를 이해할 때도 이 자산이 어느 기능을 잘하고 어느 기능이 약한지 나눠 봐야 합니다.",
    whyItMatters: "비트코인을 디지털 금으로 볼지, 결제 수단으로 볼지 판단하는 기준이 됩니다.",
    examples: [{ title: "달러", description: "세계 무역과 금융에서 가장 널리 쓰이는 법정화폐입니다." }],
    misconceptions: ["가격이 오르면 무조건 좋은 돈이라는 뜻은 아닙니다."],
    risks: ["화폐는 신뢰가 깨지면 빠르게 가치가 흔들릴 수 있습니다."],
    relatedTerms: ["가치 저장", "법정화폐", "인플레이션"],
    relatedMetricIds: ["dxy", "fed_rate"],
    prerequisites: [],
    nextLessons: ["what-is-crypto"],
    quiz: [
      {
        question: "돈의 핵심 기능이 아닌 것은?",
        options: ["가치 저장", "교환 매개", "회계 단위", "가격 보장"],
        answerIndex: 3,
        explanation: "돈은 가격을 보장하지 않습니다. 가격은 수요와 공급에 따라 변합니다.",
      },
    ],
    difficulty: "beginner",
    estimatedMinutes: 5,
  },
  {
    id: "crypto-basics",
    slug: "what-is-crypto",
    categoryId: "암호화폐란 무엇인가",
    title: "암호화폐는 무엇인가?",
    summary: "암호화폐는 블록체인 같은 네트워크에서 소유권과 거래가 기록되는 디지털 자산입니다.",
    simpleExplanation: "은행 장부 대신 네트워크가 함께 확인하는 인터넷 자산입니다.",
    analogy: "여러 사람이 같은 가계부 사본을 가지고 있어 한 사람이 몰래 내용을 바꾸기 어려운 구조입니다.",
    detailedExplanation:
      "암호화폐는 개인키로 소유권을 증명하고 네트워크 합의로 거래를 확정합니다. 코인마다 목적은 다릅니다. 비트코인은 희소성, 이더리움은 프로그램 실행, 스테이블코인은 가격 안정성을 강조합니다.",
    whyItMatters: "코인의 목적을 모르면 가격 움직임만 보고 잘못된 결론을 내리기 쉽습니다.",
    examples: [
      { title: "BTC", description: "공급량이 제한된 대표 암호화폐입니다." },
      { title: "ETH", description: "스마트 계약을 실행하는 네트워크 자산입니다." },
    ],
    misconceptions: ["모든 암호화폐가 비트코인과 같은 목적을 갖는 것은 아닙니다."],
    risks: ["해킹, 사기, 규제, 유동성 부족, 과도한 레버리지가 주요 위험입니다."],
    relatedTerms: ["블록체인", "개인키", "시가총액"],
    relatedMetricIds: ["crypto_market_cap", "btc_dominance"],
    prerequisites: ["what-is-money"],
    nextLessons: ["stablecoins"],
    quiz: [
      {
        question: "암호화폐를 이해할 때 먼저 볼 질문은?",
        options: ["왜 필요한가", "어제 올랐나", "이름이 멋진가", "광고가 많은가"],
        answerIndex: 0,
        explanation: "사용 목적과 필요한 이유를 먼저 확인해야 합니다.",
      },
    ],
    difficulty: "beginner",
    estimatedMinutes: 7,
  },
  {
    id: "stablecoin",
    slug: "stablecoins",
    categoryId: "스테이블코인",
    title: "스테이블코인은 왜 중요한가?",
    summary: "스테이블코인은 시장 안에서 현금성 대기 자금처럼 쓰입니다.",
    simpleExplanation: "코인을 팔고도 은행으로 나가지 않고 달러 비슷한 토큰으로 머무는 방법입니다.",
    analogy: "놀이공원 안에서 현금 대신 쓰는 이용권처럼, 시장 안에서 빠르게 이동하는 결제 수단입니다.",
    detailedExplanation:
      "USDT, USDC 같은 스테이블코인은 달러 가치에 맞추도록 설계됩니다. 공급량 증가는 시장 대기 자금 증가로 해석될 수 있지만, 단독으로 매수 신호라고 판단하면 안 됩니다.",
    whyItMatters: "암호화폐 시장의 유동성, 거래소 자금, 온체인 결제 흐름을 읽는 핵심 지표입니다.",
    examples: [{ title: "USDC", description: "여러 체인에서 발행되는 달러 연동 스테이블코인입니다." }],
    misconceptions: ["스테이블코인 공급 증가만으로 상승장을 확정할 수 없습니다."],
    risks: ["담보 부족, 발행사 규제, 디페깅, 체인 리스크를 확인해야 합니다."],
    relatedTerms: ["디페깅", "준비금", "유동성"],
    relatedMetricIds: ["stablecoin_supply"],
    prerequisites: ["what-is-crypto"],
    nextLessons: ["tvl"],
    quiz: [
      {
        question: "스테이블코인 공급 증가를 해석할 때 함께 봐야 할 것은?",
        options: ["시장 총액과 거래량", "로고 색상", "SNS 밈", "코인 이름 길이"],
        answerIndex: 0,
        explanation: "공급 증가가 실제 시장 유입인지 보려면 다른 지표와 함께 봐야 합니다.",
      },
    ],
    difficulty: "beginner",
    estimatedMinutes: 8,
  },
  {
    id: "tvl",
    slug: "tvl",
    categoryId: "탈중앙화 금융",
    title: "TVL은 무엇인가?",
    summary: "TVL은 디파이 프로토콜에 예치된 자산 규모를 뜻합니다.",
    simpleExplanation: "사람들이 디파이에 맡겨둔 돈의 총량에 가깝습니다.",
    analogy: "은행 예금 잔액처럼 보이지만, 암호화폐 가격 변동과 인센티브의 영향을 크게 받습니다.",
    detailedExplanation:
      "TVL은 Total Value Locked의 약자입니다. 실제 사용 수요를 보여주는 단서가 될 수 있지만, 토큰 가격 상승만으로 TVL이 늘 수도 있어 거래량, 수수료, 사용자 수와 함께 봐야 합니다.",
    whyItMatters: "온체인 생태계에 돈이 머무는지, 빠지는지 판단하는 대표 지표입니다.",
    examples: [{ title: "Aave TVL", description: "대출 프로토콜에 예치된 담보 규모입니다." }],
    misconceptions: ["TVL이 높다고 항상 좋은 프로토콜은 아닙니다."],
    risks: ["스마트 계약 해킹, 청산, 인센티브 종료 후 자금 이탈이 있습니다."],
    relatedTerms: ["DeFi", "스마트 계약", "수수료"],
    relatedMetricIds: ["defi_tvl"],
    prerequisites: ["stablecoins"],
    nextLessons: [],
    quiz: [
      {
        question: "TVL을 볼 때 주의할 점은?",
        options: ["토큰 가격 변화만으로도 변할 수 있다", "절대 줄지 않는다", "거래소 잔고와 같다", "개인키를 알려준다"],
        answerIndex: 0,
        explanation: "TVL은 예치 수량뿐 아니라 자산 가격의 영향을 받습니다.",
      },
    ],
    difficulty: "beginner",
    estimatedMinutes: 7,
  },
];
