import type { Lesson } from "@/types";

export const lessonCategories = [
  "돈과 화폐",
  "암호화폐와 블록체인",
  "비트코인과 이더리움",
  "스테이블코인과 DeFi",
  "토큰 경제학",
  "시장과 돈의 흐름",
  "온체인 데이터와 위험",
];

export const lessons: Lesson[] = [
  {
    id: "money-basics",
    slug: "what-is-money",
    categoryId: "돈과 화폐",
    title: "돈은 무엇인가?",
    summary: "돈은 가치를 저장하고, 교환하고, 가격을 비교하게 해주는 사회적 약속입니다.",
    simpleExplanation: "돈은 모두가 받아준다고 믿기 때문에 쓸 수 있는 도구입니다.",
    analogy: "동네 쿠폰이 그 동네에서만 통하듯, 돈도 사람들이 믿고 받아주는 범위가 중요합니다.",
    detailedExplanation: "돈은 가치 저장, 교환 매개, 회계 단위라는 세 가지 기능을 갖습니다. 암호화폐를 이해할 때도 이 자산이 어느 기능을 잘하고 어느 기능이 약한지 나눠 봐야 합니다.",
    whyItMatters: "금리, 달러, 유동성 같은 거시경제 지표가 암호화폐 시장에 왜 영향을 주는지 이해하는 출발점입니다.",
    examples: [{ title: "달러", description: "세계 무역과 금융에서 가장 널리 쓰이는 법정화폐입니다." }],
    misconceptions: ["가격이 오르면 무조건 좋은 돈이라는 뜻은 아닙니다.", "돈은 정부만 만들 수 있다는 생각은 암호화폐를 이해할 때 좁은 관점이 될 수 있습니다."],
    risks: ["화폐는 신뢰가 깨지면 빠르게 가치가 흔들릴 수 있습니다."],
    relatedTerms: ["법정화폐", "인플레이션", "유동성"],
    relatedMetricIds: ["global_liquidity", "fed_rate"],
    prerequisites: [],
    nextLessons: ["what-is-crypto"],
    quiz: [{ question: "돈의 핵심 기능이 아닌 것은?", options: ["가치 저장", "교환 매개", "회계 단위", "가격 보장"], answerIndex: 3, explanation: "돈은 가격을 보장하지 않습니다. 가격은 수요와 공급, 신뢰, 유동성에 따라 변합니다." }],
    difficulty: "beginner",
    estimatedMinutes: 5,
  },
  {
    id: "crypto-basics",
    slug: "what-is-crypto",
    categoryId: "암호화폐와 블록체인",
    title: "암호화폐는 무엇인가?",
    summary: "암호화폐는 블록체인 같은 네트워크에서 소유권과 거래가 기록되는 디지털 자산입니다.",
    simpleExplanation: "은행 장부 대신 네트워크가 함께 확인하는 인터넷 자산입니다.",
    analogy: "여러 사람이 같은 가계부 사본을 가지고 있어 한 사람이 몰래 내용을 바꾸기 어려운 구조와 비슷합니다.",
    detailedExplanation: "암호화폐는 개인키로 소유권을 증명하고 네트워크 합의로 거래를 확정합니다. 코인마다 목적은 다릅니다. 비트코인은 희소성, 이더리움은 프로그램 실행, 스테이블코인은 가격 안정성을 강조합니다.",
    whyItMatters: "코인의 목적을 모르면 가격 움직임만 보고 잘못된 결론을 내리기 쉽습니다.",
    examples: [{ title: "BTC", description: "공급량이 제한된 대표 암호화폐입니다." }, { title: "ETH", description: "스마트 계약을 실행하는 네트워크 자산입니다." }],
    misconceptions: ["모든 암호화폐가 비트코인과 같은 목적을 갖는 것은 아닙니다."],
    risks: ["해킹, 사기, 규제, 유동성 부족, 과도한 레버리지가 주요 위험입니다."],
    relatedTerms: ["블록체인", "개인키", "시가총액"],
    relatedMetricIds: ["crypto_market_cap", "btc_dominance"],
    prerequisites: ["what-is-money"],
    nextLessons: ["bitcoin-ethereum"],
    quiz: [{ question: "암호화폐를 이해할 때 가장 먼저 볼 질문은?", options: ["왜 필요한가", "어제 올랐나", "이름이 멋진가", "광고가 많은가"], answerIndex: 0, explanation: "사용 목적과 필요한 이유를 먼저 확인해야 합니다." }],
    difficulty: "beginner",
    estimatedMinutes: 7,
  },
  {
    id: "bitcoin-ethereum",
    slug: "bitcoin-ethereum",
    categoryId: "비트코인과 이더리움",
    title: "비트코인과 이더리움은 어떻게 다른가?",
    summary: "비트코인은 희소성과 가치 저장 논리가 강하고, 이더리움은 앱과 스마트 계약 생태계가 핵심입니다.",
    simpleExplanation: "비트코인이 디지털 금에 가깝다면, 이더리움은 금융 앱이 올라가는 인터넷 컴퓨터에 가깝습니다.",
    analogy: "비트코인은 금고 안의 금괴, 이더리움은 여러 자동 계약이 돌아가는 공용 운영체제처럼 생각할 수 있습니다.",
    detailedExplanation: "비트코인은 제한된 공급량과 검열 저항성을 강조합니다. 이더리움은 스마트 계약을 통해 디파이, NFT, 토큰 발행 같은 앱을 실행합니다. 그래서 두 자산은 같은 암호화폐라도 평가 기준이 다릅니다.",
    whyItMatters: "비트코인 도미넌스가 변할 때 시장 관심이 어디로 이동하는지 이해하는 데 필요합니다.",
    examples: [{ title: "BTC 도미넌스", description: "시장 전체에서 비트코인이 차지하는 비중입니다." }, { title: "ETH 가스비", description: "이더리움 네트워크 사용 수수료입니다." }],
    misconceptions: ["이더리움은 비트코인의 단순 복제품이 아닙니다.", "비트코인 도미넌스 하락이 항상 알트코인 강세를 의미하지는 않습니다."],
    risks: ["각 네트워크의 보안, 규제, 수수료, 확장성 위험을 따로 봐야 합니다."],
    relatedTerms: ["비트코인 도미넌스", "스마트 계약", "가스비"],
    relatedMetricIds: ["btc_dominance", "crypto_market_cap"],
    prerequisites: ["what-is-crypto"],
    nextLessons: ["stablecoins"],
    quiz: [{ question: "이더리움의 핵심 특징에 가장 가까운 것은?", options: ["스마트 계약 실행", "발행량 완전 고정", "은행 계좌 발급", "달러 가격 고정"], answerIndex: 0, explanation: "이더리움은 스마트 계약을 실행해 여러 앱과 프로토콜을 만들 수 있게 합니다." }],
    difficulty: "beginner",
    estimatedMinutes: 8,
  },
  {
    id: "stablecoin",
    slug: "stablecoins",
    categoryId: "스테이블코인과 DeFi",
    title: "스테이블코인은 왜 중요한가?",
    summary: "스테이블코인은 시장 안에서 현금성 대기 자금처럼 쓰입니다.",
    simpleExplanation: "코인을 팔고도 은행으로 나가지 않고 달러 비슷한 토큰으로 머무는 방법입니다.",
    analogy: "놀이공원 안에서 현금 대신 쓰는 이용권처럼, 시장 안에서 빠르게 이동하는 결제 수단입니다.",
    detailedExplanation: "USDT, USDC 같은 스테이블코인은 달러 가치에 맞추도록 설계됩니다. 공급량 증가는 시장 대기 자금 증가로 해석될 수 있지만, 단독으로 매수 신호라고 판단하면 안 됩니다.",
    whyItMatters: "암호화폐 시장의 유동성, 거래소 자금, 온체인 결제 흐름을 읽는 핵심 지표입니다.",
    examples: [{ title: "USDC", description: "여러 체인에서 발행되는 달러 연동 스테이블코인입니다." }],
    misconceptions: ["스테이블코인 공급 증가만으로 상승장을 확정할 수 없습니다."],
    risks: ["담보 부족, 발행사 규제, 디페깅, 체인 리스크를 확인해야 합니다."],
    relatedTerms: ["스테이블코인", "디페깅", "유동성"],
    relatedMetricIds: ["stablecoin_supply"],
    prerequisites: ["bitcoin-ethereum"],
    nextLessons: ["tvl"],
    quiz: [{ question: "스테이블코인 공급 증가를 해석할 때 함께 봐야 할 것은?", options: ["시장 총액과 거래량", "로고 색상", "SNS 밈", "코인 이름 길이"], answerIndex: 0, explanation: "공급 증가가 실제 시장 유입인지 보려면 다른 지표와 함께 봐야 합니다." }],
    difficulty: "beginner",
    estimatedMinutes: 8,
  },
  {
    id: "tvl",
    slug: "tvl",
    categoryId: "스테이블코인과 DeFi",
    title: "TVL은 무엇인가?",
    summary: "TVL은 디파이 프로토콜에 예치된 자산 규모를 뜻합니다.",
    simpleExplanation: "사람들이 디파이에 맡겨둔 돈의 총량에 가깝습니다.",
    analogy: "은행 예금 잔액처럼 보이지만, 암호화폐 가격 변동과 인센티브의 영향을 크게 받습니다.",
    detailedExplanation: "TVL은 Total Value Locked의 약자입니다. 실제 사용 수요를 보여주는 단서가 될 수 있지만, 토큰 가격 상승만으로 TVL이 늘 수도 있어 거래량, 수수료, 사용자 수와 함께 봐야 합니다.",
    whyItMatters: "온체인 생태계에 돈이 머무는지, 빠지는지 판단하는 대표 지표입니다.",
    examples: [{ title: "Aave TVL", description: "대출 프로토콜에 예치된 담보 규모입니다." }],
    misconceptions: ["TVL이 높다고 항상 좋은 프로토콜은 아닙니다."],
    risks: ["스마트 계약 해킹, 청산, 인센티브 종료 후 자금 이탈이 있습니다."],
    relatedTerms: ["TVL", "DeFi", "스마트 계약"],
    relatedMetricIds: ["defi_tvl"],
    prerequisites: ["stablecoins"],
    nextLessons: ["tokenomics"],
    quiz: [{ question: "TVL을 볼 때 주의할 점은?", options: ["토큰 가격 변화만으로도 변할 수 있다", "절대 줄지 않는다", "거래소 잔고와 같다", "개인키를 알려준다"], answerIndex: 0, explanation: "TVL은 예치 수량뿐 아니라 자산 가격의 영향을 받습니다." }],
    difficulty: "beginner",
    estimatedMinutes: 7,
  },
  {
    id: "tokenomics",
    slug: "tokenomics",
    categoryId: "토큰 경제학",
    title: "토큰 경제학은 왜 중요한가?",
    summary: "토큰 경제학은 공급량, 유통량, 보상, 락업처럼 토큰 가치에 영향을 주는 구조를 봅니다.",
    simpleExplanation: "좋은 프로젝트라도 새 토큰이 너무 많이 풀리면 가격에는 부담이 될 수 있습니다.",
    analogy: "회사 주식이 계속 새로 발행되면 기존 주주의 몫이 희석되는 것과 비슷합니다.",
    detailedExplanation: "토큰 경제학은 발행량, 최대 공급량, 유통량, 인플레이션, 락업 해제, 팀과 투자자 배분을 함께 봅니다. 기술 설명보다 실제 공급 구조가 더 큰 가격 압력이 될 때도 많습니다.",
    whyItMatters: "시가총액과 FDV를 비교해 현재 가격이 어떤 공급 구조 위에 있는지 이해할 수 있습니다.",
    examples: [{ title: "락업 해제", description: "묶여 있던 토큰이 시장에 풀리는 일정입니다." }],
    misconceptions: ["총공급량이 적으면 무조건 좋은 토큰이라는 뜻은 아닙니다."],
    risks: ["과도한 인플레이션, 보유 집중, 락업 해제 일정은 주요 위험입니다."],
    relatedTerms: ["시가총액", "FDV", "락업"],
    relatedMetricIds: ["crypto_market_cap"],
    prerequisites: ["tvl"],
    nextLessons: ["money-flow"],
    quiz: [{ question: "토큰 락업 해제가 중요한 이유는?", options: ["공급 압력이 생길 수 있어서", "블록체인이 멈춰서", "개인키가 바뀌어서", "달러 금리가 사라져서"], answerIndex: 0, explanation: "락업 해제는 새 유통 물량이 늘어나는 이벤트가 될 수 있습니다." }],
    difficulty: "intermediate",
    estimatedMinutes: 9,
  },
  {
    id: "money-flow",
    slug: "money-flow",
    categoryId: "시장과 돈의 흐름",
    title: "돈의 흐름은 어떻게 읽을까?",
    summary: "거시경제에서 위험자산, 암호화폐 시장, 체인과 프로토콜로 이어지는 자금 이동을 추정합니다.",
    simpleExplanation: "한 지표만 보지 않고 여러 신호가 같은 방향을 가리키는지 확인하는 과정입니다.",
    analogy: "강물의 방향을 한 곳만 보고 판단하지 않고, 여러 지류와 수위를 함께 보는 것과 비슷합니다.",
    detailedExplanation: "돈의 흐름은 확정 사실이 아니라 추정입니다. 금리, 유동성, 스테이블코인 공급, 거래소 활동, DeFi TVL, 도미넌스 같은 지표를 함께 보고 유입·유출 가능성을 판단합니다.",
    whyItMatters: "시장이 왜 오르거나 흔들리는지 설명할 때 가격보다 먼저 자금의 경로를 볼 수 있습니다.",
    examples: [{ title: "스테이블코인 증가 + 시장 총액 증가", description: "대기 자금과 위험자산 선호가 함께 커지는지 보는 조합입니다." }],
    misconceptions: ["두세 개 지표만으로 시장 방향을 확정할 수 없습니다."],
    risks: ["데이터 지연, 출처 차이, 단기 이벤트, 레버리지 청산이 해석을 왜곡할 수 있습니다."],
    relatedTerms: ["유동성", "비트코인 도미넌스", "TVL"],
    relatedMetricIds: ["global_liquidity", "crypto_market_cap", "stablecoin_supply", "defi_tvl"],
    prerequisites: ["tokenomics"],
    nextLessons: ["onchain-risk"],
    quiz: [{ question: "돈의 흐름을 볼 때 가장 안전한 태도는?", options: ["여러 지표의 근거와 반대 신호를 함께 본다", "하나의 지표만 믿는다", "높은 수익률 문구를 따른다", "데이터 없음은 0으로 본다"], answerIndex: 0, explanation: "돈의 흐름은 여러 지표의 조합과 반대 신호를 함께 봐야 합니다." }],
    difficulty: "intermediate",
    estimatedMinutes: 10,
  },
  {
    id: "onchain-risk",
    slug: "onchain-risk",
    categoryId: "온체인 데이터와 위험",
    title: "온체인 데이터와 위험은 어떻게 봐야 할까?",
    summary: "지갑, 거래, TVL, 브릿지 흐름 같은 온체인 데이터는 투명하지만 해석에는 주의가 필요합니다.",
    simpleExplanation: "블록체인에 남은 발자국을 읽는 일이지만, 발자국만 보고 사람의 의도를 확정할 수는 없습니다.",
    analogy: "상점의 방문자 수를 보면 관심을 알 수 있지만, 모두가 구매한 것은 아닌 것과 비슷합니다.",
    detailedExplanation: "온체인 데이터는 활성 주소, 거래 수, 수수료, TVL, 브릿지 유입·유출 등을 포함합니다. 하지만 에어드롭 작업, 봇, 인센티브, 가격 변화가 숫자를 부풀릴 수 있습니다.",
    whyItMatters: "암호화폐는 공개 데이터가 많기 때문에, 숫자의 의미와 한계를 함께 이해하면 사기와 과열을 피하는 데 도움이 됩니다.",
    examples: [{ title: "브릿지 유입", description: "다른 체인에서 자금이 이동해 들어오는 흐름입니다." }],
    misconceptions: ["활성 주소가 늘면 무조건 실제 사용자가 늘었다고 볼 수는 없습니다."],
    risks: ["스마트 계약 해킹, 브릿지 해킹, 지갑 피싱, 관리자 권한 위험이 있습니다."],
    relatedTerms: ["온체인", "브릿지", "개인키"],
    relatedMetricIds: ["defi_tvl"],
    prerequisites: ["money-flow"],
    nextLessons: [],
    quiz: [{ question: "온체인 데이터를 볼 때 주의할 점은?", options: ["봇과 인센티브가 숫자를 부풀릴 수 있다", "항상 완벽한 진실이다", "거래소 가격과 무관하다", "보안 위험을 없애준다"], answerIndex: 0, explanation: "온체인 데이터는 투명하지만 봇, 인센티브, 가격 변화 때문에 해석이 왜곡될 수 있습니다." }],
    difficulty: "intermediate",
    estimatedMinutes: 9,
  },
];
