import type { GlossaryTerm } from "@/types";

export const glossaryTerms: GlossaryTerm[] = [
  {
    id: "blockchain",
    term: "블록체인",
    englishTerm: "Blockchain",
    oneLineDefinition: "거래 기록을 블록 단위로 연결해 여러 참여자가 함께 검증하는 장부입니다.",
    simpleExplanation: "모두가 같은 거래 기록을 나눠 들고 있어 몰래 바꾸기 어렵습니다.",
    detailedExplanation: "블록체인은 거래 묶음인 블록을 시간순으로 연결하고, 합의 규칙으로 새 기록을 확정합니다.",
    relatedTerms: ["합의", "노드", "해시"],
    category: "기초",
    difficulty: "beginner",
  },
  {
    id: "market-cap",
    term: "시가총액",
    englishTerm: "Market Cap",
    oneLineDefinition: "가격에 유통량을 곱한 자산의 시장 규모입니다.",
    simpleExplanation: "그 코인이 시장에서 어느 정도 규모로 평가받는지 보는 숫자입니다.",
    detailedExplanation: "시가총액은 가격만 보는 것보다 규모 비교에 유용하지만, 유동성과 락업 구조를 함께 봐야 합니다.",
    example: "가격 10달러, 유통량 1억 개라면 시가총액은 10억 달러입니다.",
    relatedTerms: ["FDV", "유통량", "락업"],
    category: "시장 지표",
    difficulty: "beginner",
  },
  {
    id: "tvl",
    term: "TVL",
    englishTerm: "Total Value Locked",
    oneLineDefinition: "디파이 프로토콜에 예치된 자산의 총 가치입니다.",
    simpleExplanation: "디파이에 맡겨진 돈의 규모를 보는 지표입니다.",
    detailedExplanation: "TVL은 생태계 유동성을 보여주지만, 자산 가격 변동과 인센티브에 의해 부풀려질 수 있습니다.",
    relatedTerms: ["DeFi", "유동성", "스마트 계약"],
    category: "온체인",
    difficulty: "beginner",
  },
  {
    id: "stablecoin",
    term: "스테이블코인",
    englishTerm: "Stablecoin",
    oneLineDefinition: "달러 같은 법정화폐 가치에 맞추도록 설계된 암호화폐입니다.",
    simpleExplanation: "시장 안에서 현금처럼 대기하거나 이동하는 데 자주 씁니다.",
    detailedExplanation: "스테이블코인은 담보, 발행사, 준비금, 규제 리스크를 확인해야 합니다.",
    relatedTerms: ["USDT", "USDC", "디페깅"],
    category: "자산 분류",
    difficulty: "beginner",
  },
];
