import type { GlossaryTerm } from "@/types";

export const glossaryTerms: GlossaryTerm[] = [
  {
    id: "blockchain",
    term: "블록체인",
    englishTerm: "Blockchain",
    oneLineDefinition: "거래 기록을 블록 단위로 연결해 여러 참여자가 함께 검증하는 장부입니다.",
    simpleExplanation: "모두가 같은 거래 기록을 나눠 들고 있어 몰래 바꾸기 어렵습니다.",
    detailedExplanation: "블록체인은 거래 묶음인 블록을 시간순으로 연결하고, 합의 규칙으로 새 기록을 확정합니다. 중앙 서버 하나에 의존하지 않는다는 점이 핵심입니다.",
    relatedTerms: ["합의", "노드", "해시"],
    category: "기초",
    difficulty: "beginner",
  },
  {
    id: "private-key",
    term: "개인키",
    englishTerm: "Private Key",
    oneLineDefinition: "지갑 안의 자산을 움직일 수 있게 해주는 비밀 열쇠입니다.",
    simpleExplanation: "개인키를 가진 사람이 자산을 보낼 수 있습니다.",
    detailedExplanation: "개인키는 지갑 소유권을 증명하는 핵심 정보입니다. 다른 사람에게 노출되면 자산을 되돌리기 어렵기 때문에 안전하게 보관해야 합니다.",
    relatedTerms: ["지갑", "시드문구", "서명"],
    category: "보안",
    difficulty: "beginner",
  },
  {
    id: "market-cap",
    term: "시가총액",
    englishTerm: "Market Cap",
    oneLineDefinition: "가격에 유통량을 곱한 자산의 시장 규모입니다.",
    simpleExplanation: "그 코인이 시장에서 어느 정도 규모로 평가받는지 보는 숫자입니다.",
    detailedExplanation: "시가총액은 가격만 보는 것보다 규모 비교에 유용하지만, 유동성과 락업 구조를 함께 봐야 합니다.",
    example: "가격 10달러, 유통량 1억 개라면 시가총액은 10억 달러입니다.",
    relatedTerms: ["FDV", "유통량", "락업"],
    category: "시장 지표",
    difficulty: "beginner",
  },
  {
    id: "btc-dominance",
    term: "비트코인 도미넌스",
    englishTerm: "Bitcoin Dominance",
    oneLineDefinition: "암호화폐 전체 시가총액에서 비트코인이 차지하는 비중입니다.",
    simpleExplanation: "시장 관심이 비트코인 쪽에 더 쏠리는지 보는 지표입니다.",
    detailedExplanation: "도미넌스가 오르면 비트코인이 상대적으로 강하다는 해석이 가능하지만, 전체 시장 하락 중에도 도미넌스가 오를 수 있어 맥락이 중요합니다.",
    relatedTerms: ["시가총액", "알트코인", "위험자산"],
    category: "시장 지표",
    difficulty: "beginner",
  },
  {
    id: "stablecoin",
    term: "스테이블코인",
    englishTerm: "Stablecoin",
    oneLineDefinition: "달러 같은 법정화폐 가치에 맞추도록 설계된 암호화폐입니다.",
    simpleExplanation: "시장 안에서 현금처럼 대기하거나 이동하는 데 자주 씁니다.",
    detailedExplanation: "스테이블코인은 담보, 발행사, 준비금, 규제 리스크를 확인해야 합니다. 공급량 증가는 대기 자금의 단서가 될 수 있지만 단독 매수 신호는 아닙니다.",
    relatedTerms: ["USDT", "USDC", "디페깅"],
    category: "자산 분류",
    difficulty: "beginner",
  },
  {
    id: "tvl",
    term: "TVL",
    englishTerm: "Total Value Locked",
    oneLineDefinition: "디파이 프로토콜에 예치된 자산의 총 가치입니다.",
    simpleExplanation: "디파이에 맡겨진 돈의 규모를 보는 지표입니다.",
    detailedExplanation: "TVL은 생태계 유동성을 보여주지만, 자산 가격 변동과 인센티브에 의해 부풀려질 수 있습니다.",
    relatedTerms: ["DeFi", "유동성", "스마트 계약"],
    category: "온체인",
    difficulty: "beginner",
  },
  {
    id: "defi",
    term: "DeFi",
    englishTerm: "Decentralized Finance",
    oneLineDefinition: "블록체인 위에서 예치, 대출, 교환 같은 금융 기능을 구현한 영역입니다.",
    simpleExplanation: "은행 앱처럼 보이지만 중개자 대신 스마트 계약이 처리합니다.",
    detailedExplanation: "DeFi는 DEX, 대출, 파생상품, 스테이킹 등을 포함합니다. 투명성이 장점이지만 스마트 계약 해킹과 청산 위험도 큽니다.",
    relatedTerms: ["TVL", "스마트 계약", "DEX"],
    category: "금융 앱",
    difficulty: "beginner",
  },
  {
    id: "smart-contract",
    term: "스마트 계약",
    englishTerm: "Smart Contract",
    oneLineDefinition: "조건이 맞으면 자동으로 실행되는 블록체인 프로그램입니다.",
    simpleExplanation: "사람이 매번 확인하지 않아도 코드가 약속을 실행합니다.",
    detailedExplanation: "스마트 계약은 DeFi와 NFT 같은 앱의 기반입니다. 코드 오류나 관리자 권한이 있으면 큰 손실로 이어질 수 있습니다.",
    relatedTerms: ["이더리움", "DeFi", "가스비"],
    category: "기술",
    difficulty: "beginner",
  },
  {
    id: "liquidity",
    term: "유동성",
    englishTerm: "Liquidity",
    oneLineDefinition: "자산을 큰 가격 충격 없이 사고팔 수 있는 정도입니다.",
    simpleExplanation: "거래할 돈과 상대방이 충분하면 유동성이 높다고 봅니다.",
    detailedExplanation: "유동성은 시장 전체의 위험 선호와 가격 변동성에 큰 영향을 줍니다. 거래량, 호가, 스테이블코인 공급 등을 함께 봅니다.",
    relatedTerms: ["거래량", "스테이블코인", "위험자산"],
    category: "시장 지표",
    difficulty: "beginner",
  },
  {
    id: "bridge",
    term: "브릿지",
    englishTerm: "Bridge",
    oneLineDefinition: "서로 다른 블록체인 사이로 자산을 이동시키는 통로입니다.",
    simpleExplanation: "체인 사이를 건너는 다리 역할을 합니다.",
    detailedExplanation: "브릿지는 체인 간 자금 이동을 보여주는 중요한 통로지만, 해킹 사고가 자주 발생한 영역이기도 합니다.",
    relatedTerms: ["온체인", "DeFi", "체인"],
    category: "온체인",
    difficulty: "intermediate",
  },
];
